### ISSUE TITLE
BSD grep not detected properly :)

### ISSUE THREAD

**Issue by VincentKempers** [wrynegade/scwrypts#1]
When using BSD grep no warning shows up reminding you to use the (right) GNU grep.
```
 /usr/bin/grep --version
grep (BSD grep, GNU compatible) 2.6.0-FreeBSD
```

**Comment by wrynegade** [comment]
Ahh yeah that's because of https://github.com/wrynegade/scwrypts/blob/6b15491066098cf68c9b6be484e887047c7155bb/zsh/lib/utils/dependencies.zsh#L40

Those tricksters have fooled me yet again!

**Comment by wrynegade** [comment]
*"GNU compatible"* lmao

**Comment by VincentKempers** [comment]
![greeeeeeeeep](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExc3JtcW1semFiNGJuaHc2NHlxZzkxazR1cm52cGEybHFqamNiYnhkaCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/KeTVw7VjcTJok/giphy.gif)

_BSD GREEEEEEPP!_

**Comment by wrynegade** [comment]
Although not particularly elegant, there's not a really standard output from all the `--version` outputs of these utilities, so [I've included a fix](https://github.com/wrynegade/scwrypts/blob/768bd1444e122e594d4615131f2143f89b2beb05/zsh/lib/utils/dependencies.zsh#L40) which detects this case in addition to the previous checks to help throw warnings on BSD utilties.

This is live as of the [4.1.3 release](https://github.com/wrynegade/scwrypts/commit/768bd1444e122e594d4615131f2143f89b2beb05)
